spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=GestionDeProductos2025;encrypt=false
spring.datasource.username=ProyectoEntrevista
spring.datasource.password=clave123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver